### ISSUE TITLE
How to customize the "Meta table" for special Model.

### ISSUE THREAD

**Issue by RJustice** [Zoha/laravel-meta#1]
Like  Post Model has default meta table, 
but User Model may need another meta table, like user_metas.

**Comment by RJustice** [comment]
If I create a new Model inheritance  \Zoha\Meta\Models\Meta, and set $table to Meta table name "user_meta",  but all trait MetableBase , GetMeta ... use the default Meta Model ...

**Comment by Zoha** [comment]
Why do you want to create a separate table for user's model meta?
Meta uses [polymorphic relationship](https://laravel.com/docs/5.6/eloquent-relationships#polymorphic-relations), which allows you to use a table for all models.
For example, for your User model, the value of the column `owner_type` will be equal to `App\User`. And for your posts model, the value of this column will be equal to `App\Post`. so in database results, there will be no conflict
Or maybe I did not understand your purpose correctly!
Can you explain better?

**Comment by RJustice** [comment]
Yes, I know `owner_type` for more Models.  
Whether this will cause the table data volume to increase too quickly, leading to slow queries ?

**Comment by Zoha** [comment]
As far as I know the physical database size or number of records doesn't matter. what matters is the number of queries . 
In this package, I tried to minimize the number of queries.
Even if you use `withMeta` method for eager loading , only one query will be used for getting all meta data from database .

**Comment by Zoha** [comment]
Anyway, thanks for your suggestion.
I'm trying to add this feature to later versions .

**Comment by RJustice** [comment]
Thanks

**Comment by Zoha** [comment]
I release version 1.5 . Now you can use separate meta table for each of your models.

[Custom Meta Table](https://github.com/ZohaBanam/laravel-meta#custom-meta-table)
