### ISSUE TITLE
composer.json has the wrong source key

### ISSUE THREAD

**Issue by XGhozt** [Zoha/laravel-meta#10]
When I installed on a production environment, it installed version 1.1. Seemed to work locally but the files in my vendor folder on the server were very outdated.

**Comment by Zoha** [comment]
please share your composer.json file

**Comment by XGhozt** [comment]
I was using the one from this package.
https://github.com/Zoha/laravel-meta/blob/master/composer.json

```   
    "license": "MIT",
	"source": {
        "url": "https://github.com/ZohaBanam/laravel-meta.git",
        "type": "git",
		"reference": "0ac3f7b"
```

My production environment was installing 0ac3f7b

My composer.json had this:

`"zoha/laravel-meta": "^1.7"`

**Comment by Zoha** [comment]
please execute `composer update` to update your composer.lock file and see if you still have this problem.

**Comment by XGhozt** [comment]
I tried that a few times. When I forked the repo and updated composer.json manually then it worked fine.
