### ISSUE TITLE
Soft Deletes in laravel-meta

### ISSUE THREAD

**Issue by Alexlytle** [Zoha/laravel-meta#18]
First off thank you so much for this wonderful package. Its a life saver coming from the wordpress world. Im wondering what would be the proper way to handle soft deletes ?

**Comment by Zoha** [comment]
HI @Alexlytle, thank you for using this package
when you soft delete a model, its meta still remains in the DB, if you want to soft delete the meta as well ( don't see any reason for it ) you can soft delete meta directly, just use Zoha\Meta\Models\meta model
remember to filter metas with `owner_id` and `owner_type` cols
also use correct meta table name
