### ISSUE TITLE
Migrations: Publish vs loading

### ISSUE THREAD

**Issue by fullstackfool** [Zoha/laravel-meta#22]
Automatically loading the migrations can make it difficult for the end-user to customise them. Consider publishing them instead to allow the developer to make any desired alterations.

https://github.com/Zoha/laravel-meta/blob/2de15acb4f3c770d5fa19c7a37d1ca79849e92c2/src/Meta/MetaServiceProvider.php#L51-L54

**Comment by Zoha** [comment]
thanks @fullstackfool for the suggestion.
I think meta to be manipulated but its a good feature that can be added in next version 
but if you need a workaround solution you can customize your model meta table and create a custom migration for it
