### ISSUE TITLE
How to WhereMetaJsonContains in Package

### ISSUE THREAD

**Issue by mehrshaddarzi** [Zoha/laravel-meta#23]
Hi,
When Use Collection or array type for meta, how to query in Builder?

![1234](https://user-images.githubusercontent.com/949491/164959000-79a3fd17-8956-4986-8faa-6c702866f153.PNG)

when create attachment meta , how to query when we want all projectt tha has attachment with 3 or 5?

```php
\App\Models\Project::whereMetaIn('attachment', ['3' , '5'])->get();
```

This Code Not Work?
Please Help

**Comment by Zoha** [comment]
hello @mehrshaddarzi 
unfortunately, there isn't any direct way to do this in this version 
but for solving your problem I suggest using this hacky way ( consider poorer performance as well )

`Project::whereMeta("attachment", "like", '%"1"%')->orWhereMeta("attachment", "like", '%"2"%')->get()`

but maybe the better way is to change your metadata structure, I suggest to don't using the meta value as a JSON that you want to filter data with

for example, you can use something like this maybe 

```
attachments_count = 3
attachment_1 = "123"
attachment_2 = "456"
attachment_3 = "789"
```
