### ISSUE TITLE
How to use whereMetaHas in pivot table

### ISSUE THREAD

**Issue by stefanomarra** [Zoha/laravel-meta#25]
Hi there, firstly, thanks for this great package, I love it, it's working great so far.
However, I have some issues when using it in a pivot table.

I use meta in a pivot table where I store some user data related to the organization he belongs to.

I'm unable to query a user based on a meta stored in this pivot table.

Example:
I want to get all users that has a specific meta (e.g. `account_id`) inside the pivot table. Any ideas on how I can achieve this?

**Comment by Zoha** [comment]
hi @stefanomarra 
thank you for using this package 
all the clause methods are using the native Laravel methods 
so if you have a more complex query that does not exist on the package you can always create a custom method yourself 
you can see the implementation of [whereMeta  here](https://github.com/Zoha/laravel-meta/blob/a65da4aa89d95251d523fb97d489990c2fb0142d/src/Meta/Traits/MetaClauses.php#L75) 
and create another method ( based on it ) that resolves your needs
