### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by nwconsulting** [Zoha/laravel-meta#26]
Hiya

Well done for creating a great package.

I was wondering if there is a way to be able to store permissions against a meta key?

What I need to be able to do is store which users/teams (using Jetstream) can read, edit, delete the metatag.

Then some way link that to Laravels search so that only those users/teams with read permission see results in the search.

Thanks for any help you can provide.

Do you plan on making a paid version with extra features?

Cheers

Nathan

**Comment by Zoha** [comment]
hi @nwconsulting and thank you for using this package 
about your question, if I understand it well if you want to do the permissions logic on the app level this package can't help you but even tho IMO is better to separate this logic from this package
remember that this package is for saving and querying on the database which is a separate concept of permissions and roles 
you should create a higher-level logical code to check these permissions 

and about the paid version, the answer is no, and it will not have any paid version in the future as well👍
