### ISSUE TITLE
new release please

### ISSUE THREAD

**Issue by necenzurat** [Zoha/laravel-meta#7]
Please do a release.

**Comment by Zoha** [comment]
Is there a problem with the package?
or you need new feature?

**Comment by necenzurat** [comment]
neither, but in order for composer to work, you need to do a release here https://github.com/Zoha/laravel-meta/releases so that it will go to packagist -> https://packagist.org/packages/zoha/laravel-meta so when you composer update, the newest version will be installed. 
basically after every update you need to make a release, increment the version and packagist will auto update if it's set up.

Thanks for the package, it's super useful.

**Comment by Zoha** [comment]
new version was released `1.6.1`
https://github.com/Zoha/laravel-meta/releases/tag/1.6.1
also if you have any idea for making this package better let me know.

**Comment by necenzurat** [comment]
packagist still not updated :(

**Comment by Zoha** [comment]
it is usually updated with a delay.
however I did it manually

**Comment by necenzurat** [comment]
Can you do a new release please?
